const express = require('express')
const { registerUser, onboardUser, verifyOtp, loginUser, sendVerificationCode, updatePassword, searchRestaurant, getRulesAndPolicy, updateUserImage, getMe } = require('../services/UserService')
const validateToken = require('../middleware/validateToken')
const { addOrRemoveFavourite, getFavourites } = require('../services/FavouriteService')
const router = express.Router()

router.post('/register', registerUser)
router.post('/onboard-user', onboardUser)
router.post('/verify-otp', verifyOtp)
router.post('/login', loginUser)
router.post('/search', searchRestaurant)
router.get('/rules', getRulesAndPolicy)
router.post('/send-otp', validateToken, sendVerificationCode)
router.post('/update-password', validateToken, updatePassword)
router.post('/update-image', validateToken, updateUserImage)
router.get('/me', validateToken, getMe)
router.post('/add-favourite', validateToken, addOrRemoveFavourite)
router.get('/get-favourites', validateToken, getFavourites)

module.exports = router